--- !ditz.rubyforge.org,2008-03-06/project 
name: tamanegi
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: tamanegi
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.0.7
  status: :released
  release_time: 2008-04-15 02:12:56.059373 Z
  log_events: 
  - - 2008-04-15 02:12:18.016977 Z
    - Stoyan Zhekov <zh@zhware.net>
    - created
    - Switch to open-uri() for feed fetching.
  - - 2008-04-15 02:12:56.059574 Z
    - Stoyan Zhekov <zh@zhware.net>
    - released
    - bugs tracking by ditz-0.2 (bugs/ dir).
- !ditz.rubyforge.org,2008-03-06/release 
  name: release-0.0.8
  status: :released
  release_time: 2008-04-22 03:20:05.786722 Z
  log_events: 
  - - 2008-04-16 03:35:45.037454 Z
    - Stoyan Zhekov <zh@zhware.net>
    - created
    - Get ready for sequel-1.4 (eager loading)
  - - 2008-04-22 03:20:05.786746 Z
    - Stoyan Zhekov <zh@zhware.net>
    - released
    - See the CHANGELOG for details.
- !ditz.rubyforge.org,2008-03-06/release 
  name: release-0.0.9
  status: :released
  release_time: 2008-05-13 01:35:29.822392 Z
  log_events: 
  - - 2008-04-22 05:09:36.654538 Z
    - Stoyan Zhekov <zh@zhware.net>
    - created
    - Maybe will try to solve favicon.ico problem or stop supporting web frontend at all.
  - - 2008-05-13 01:35:29.822392 Z
    - Stoyan Zhekov <zh@zhware.net>
    - released
    - Mostly bugfixes. arcstyle merged to the master branch.
- !ditz.rubyforge.org,2008-03-06/release 
  name: release-0.0.10
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-05-14 03:41:57.517904 Z
    - Stoyan Zhekov <zh@zhware.net>
    - created
    - Will try to keep it just bugfix release, no new features planed.
